### PR TITLE
Documentation update

### PR DESCRIPTION
**Pull request by answeb**
Hi, I added documentation about how to implement custom policies and override views
Many thanks for your work !

### CODE REVIEW

**Review by tomirons — CHANGES_REQUESTED** [review]
I think it would be much better if we could publish the files via `artisan vendor:publish`.

**Comment by answeb** [comment]
OK I didn't have the time to implement this.
I'll try to, but no guarantee ;)

**Comment by answeb** [comment]
No problem for the resources views, but the policy files are a bit different.
Do you still think I need to write the code to publish the policies ?

**Comment by tomirons** [comment]
Nah, you can skip the policies.

**Pull request merged**
