### PR TITLE
retain formatting option when creating 1st post of discussion

### PR DESCRIPTION
**Pull request by answeb**
When creating a discussion, the formatting option (rich/plain) is not used

### CODE REVIEW

**Comment by andreaselia** [comment]
Thank you, @answeb!

**Comment by answeb** [comment]
You're welcome !
How can I get this fix in my project ? I'm using `^1.4` in my `composer.json`.

**Comment by andreaselia** [comment]
I'll take a release now, and once a release is ready, you can run `composer update andreaselia/laravel-firefly`

**Comment by andreaselia** [comment]
Release has been tagged @answeb 👍

**Pull request merged**
